default:
  indices:
  - wb
  - bf
  surveys:
    selection:
    - document_id
    - location_id
    - year
    - month
    - day
  model:
    trim:
      overdispersion: true

wb:
  taxa:
  - MX.34535
  - MX.33954
  - MX.34553
#  - MX.26931
#  - MX.26928
#  - MX.26926
  - MX.34616
  - MX.30504
  - MX.36358
  - MX.29011
  - MX.36351
  - MX.30453
  - MX.36356
  - MX.29008
  - MX.34542
#  - MX.37095
  filters:
    date_range_ymd:
    - "1958-12-01"
    - ""
    date_range_md:
    - "12-01"
    - "01-31"
    collection: HR.39
  surveys:
    process:
    - shift_year_winter
    - pick_first_survey_in_year
  counts:
    selection:
    - document_id
    - abundance
    process:
    - zero_fill
    - remove_all_zero_locations
  model:
    trim:
      base_year: 1959
      overdispersion: false

bf:
  taxa:
  - MX.60914
  - MX.60916
  - MX.60767
  - MX.60970
  - MX.60772
  - MX.60908
  - MX.60876
  - MX.60859
  - MX.60889
  - MX.60890
  - MX.60884
  - MX.60811
  - MX.60745
  - MX.60830
  - MX.60965
  - MX.60968
  - MX.60865
  - MX.60979
  - MX.60863
  - MX.60931
  - MX.60878
  - MX.60794
  - MX.60957
  - MX.60958
  - MX.60763
  - MX.60944
  - MX.60821
  - MX.60816
  - MX.60819
  - MX.60939
  - MX.60920
  - MX.60755
  - MX.60730
  - MX.60953
  - MX.60778
  - MX.60854
  - MX.60855
  - MX.60925
  - MX.60866
  - MX.60867
  - MX.60735
  - MX.60809
  - MX.60877
  - MX.60799
  - MX.60749
  filters:
    date_range_ymd:
    - "1999-05-16"
    - ""
    date_range_md:
    - "05-16"
    - "08-31"
    collection: HR.3431
  surveys:
    process:
    - require_seven_fortnights
    - require_gt_two_years
    - pick_first_survey_in_fortnight
  counts:
    selection:
    - document_id
    - section
    - abundance
    process:
    - sum_over_sections
    - zero_fill
    - sum_over_fortnights
    - remove_all_zero_locations
    - remove_initial_zero_years
  model:
    trim:
      base_year: 2001
