default:
  indices:
#  - fb
  - wb
  - bf
  surveys:
    selection:
    - document_id
    - location_id
    - year
    - month
    - day
  counts:
    abundance: abundance

# fb:
#   taxa:
#   - code: MX.27328
#     start_year: 2006
#   - code: MX.27527
#   - code: MX.27613
#   - code: MX.32065
#   - code: MX.32132
#   - code: MX.32163
#   - code: MX.32213
#   - code: MX.32949
#   - code: MX.33117
#   - code: MX.33936
#   - code: MX.37142
#   - code: MX.36817
#   - code: MX.36589
#     start_year: 2006
#   - code: MX.35154
#   filters:
#     date_range_ymd:
#     - "1979-01-01"
#     - ""
#   collection:
#   - HR.157
#   - HR.61
#   counts:
#     abundance: pair_abundance
#     selection:
#     - document_id
#     - pair_abundance
#   model:
#     trim:
#       base_year: 2006
#       overdispersion: false
#       survey_process:
#       - pick_first_survey_in_year
#       - require_gt_two_years
#       count_process:
#       - zero_fill
#       - sum_by_event
#       - set_start_year
#       - remove_all_zero_locations

wb:
  taxa:
  - code: MX.34535
  - code: MX.33954
  - code: MX.34553
  - code: MX.26931
  - code: MX.26928
  - code: MX.26926
  - code: MX.34616
  - code: MX.30504
  - code: MX.36358
  - code: MX.29011
  - code: MX.36351
  - code: MX.30453
  - code: MX.36356
  - code: MX.29008
  - code: MX.34542
  - code: MX.37095
  filters:
    date_range_ymd:
    - "1958-12-01"
    - ""
    date_range_md:
    - "12-01"
    - "01-31"
    collection: HR.39
  counts:
    selection:
    - document_id
    - abundance
  model:
    trim:
      base_year: 1959
      overdispersion: false
      surveys_process:
      - shift_year_winter
      - pick_first_survey_in_year
      counts_process:
      - zero_fill
      - remove_all_zero_locations

bf:
  taxa:
  - code: MX.60914
  - code: MX.60916
  - code: MX.60767
  - code: MX.60970
  - code: MX.60772
  - code: MX.60908
    start_year: 2000
  - code: MX.60876
  - code: MX.60859
  - code: MX.60889
  - code: MX.60890
  - code: MX.60884
  - code: MX.60811
  - code: MX.60745
  - code: MX.60830
  - code: MX.60965
  - code: MX.60968
  - code: MX.60865
  - code: MX.60979
  - code: MX.60863
  - code: MX.60931
  - code: MX.60878
  - code: MX.60794
  - code: MX.60957
  - code: MX.60958
  - code: MX.60763
  - code: MX.60944
  - code: MX.60821
  - code: MX.60816
  - code: MX.60819
  - code: MX.60939
  - code: MX.60920
  - code: MX.60755
  - code: MX.60730
  - code: MX.60953
  - code: MX.60778
  - code: MX.60854
  - code: MX.60855
  - code: MX.60925
  - code: MX.60866
  - code: MX.60867
  - code: MX.60735
    start_year: 2000
  - code: MX.60809
    start_year: 2000
  - code: MX.60877
  - code: MX.60799
  - code: MX.60749
  extra_taxa:
  - code: MX.60858
  - code: MX.60791
  - code: MX.60775
  - code: MX.60777
  - code: MX.60910
  - code: MX.60911
  filters:
    collection: HR.3431
  counts:
    selection:
    - document_id
    - section
    - abundance
    has_value:
    - section
    - document_id
  model:
    trim:
      overdispersion: true
      base_year: 2001
      surveys_process:
      - require_seven_fortnights
      - require_gt_two_years
      - pick_first_survey_in_fortnight
      counts_process:
      - sum_over_sections
      - zero_fill
      - sum_by_event
      - set_start_year
      - remove_all_zero_locations
