version: "3.2"

services:
  postgres:
    image: postgres
    restart: always
    environment:
      - "POSTGRES_USER=${PGUSER}"
      - "POSTGRES_PASSWORD=${PGPASSWORD}"
    volumes:
      - "postgres:/var/lib/postgresql/data"
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
      args:
        - "PGUSER=${PGUSER}"
        - "PGPASSWORD=${PGPASSWORD}"
        - "FINBIF_ACCESS_TOKEN=${FINBIF_ACCESS_TOKEN}"
    restart: always
    tmpfs:
      - "/tmpsvgs"
    ports:
      - "8000:8000"

volumes:
  postgres:
