version: "3.2"
services:
  api:
    build:
      context: .
    environment:
    - "PGHOST=postgres"
    - "PGUSER=postgres"
    - "PGPASSWORD=1234"
    - "FINBIF_ACCESS_TOKEN=dummy"
    depends_on:
    - postgres
  postgres:
    image: postgres
    environment:
    - "POSTGRES_USER=postgres"
    - "POSTGRES_PASSWORD=1234"
