kind: Template
apiVersion: v1
parameters:
  - name: APP
    required: true
    value: fin-biodiv-indicators
  - name: APP_TITLE
    required: true
    value: "Finnish Biodiversity Indicators"
  - name: APP_PORT
    required: true
    value: "8000"
  - name: HOME
    required: true
    value: /home/user
  - name: HEALTH
    required: true
    value: healthz
  - name: LIVENESS_PERIOD
    required: true
    value: "30"
  - name: FAILURE_THRESHOLD
    required: true
    value: "5"
  - name: READINESS_PERIOD
    required: true
    value: "5"
  - name: LOG
    required: true
    value: log-monitor
  - name: LOG_PORT
    required: true
    value: "3838"
  - name: LOG_DIR
    required: true
    value: logs
  - name: TMP_DIR
    required: true
    value: tmp
  - name: DB
    required: true
    value: postgres
  - name: DB_IMAGE
    required: true
    value: "172.30.1.1:5000/openshift/postgresql@sha256:b681d78125361519180a6ac05242c296f8906c11eab7e207b5ca9a89b6344392"
  - name: DB_PORT
    required: true
    value: "5432"
  - name: DB_DIR
    required: true
    value: /var/lib/pgsql/data
  - name: GIT_HOST
    required: true
    value: https://github.com
  - name: ORG
    required: true
    value: luomus
  - name: PROD
    required: true
    value: master
  - name: DEV
    required: true
    value: dev
  - name: TAG
    required: true
    value: latest
  - name: STORAGE
    required: true
    value: "40Gi"
  - name: SMALL_STORAGE
    required: true
    value: "3Gi"
  - name: REPS
    required: true
    value: "1"
  - name: HOST
    required: true
  - name: SUBDOMAIN
    required: true
  - name: LOG_HOST
    required: true
  - name: LOG_SUBDOMAIN
    required: true
  - name: DB_PASSWORD
    required: true
  - name: FINBIF_ACCESS_TOKEN
    required: true
  - name: FINBIF_API
    required: true
  - name: FINBIF_WAREHOUSE_QUERY
    required: true
  - name: FINBIF_EMAIL
    required: true
  - name: DEV_DB_PASSWORD
    required: true
  - name: DEV_FINBIF_ACCESS_TOKEN
    required: true
  - name: DEV_FINBIF_API
    required: true
  - name: DEV_FINBIF_WAREHOUSE_QUERY
    required: true
  - name: GITHUB_SECRET
    required: true
    generate: expression
    from: "[a-zA-Z0-9]{20}"
metadata:
  name: ${APP}
objects:
- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: ${APP}
    labels:
      app: ${APP}
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ${APP}:${TAG}
    source:
      type: Git
      git:
        uri: ${GIT_HOST}/${ORG}/${APP}.git
        ref: ${PROD}
    strategy:
      type: Docker
    triggers:
    - type: ConfigChange
    - type: GitHub
      github:
        secret: ${GITHUB_SECRET}
- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: ${DEV}-${APP}
    labels:
      app: ${APP}
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ${DEV}-${APP}:${TAG}
    source:
      type: Git
      git:
        uri: ${GIT_HOST}/${ORG}/${APP}.git
        ref: ${DEV}
    strategy:
      type: Docker
    triggers:
    - type: ConfigChange
    - type: GitHub
      github:
        secret: ${GITHUB_SECRET}
- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: ${LOG}
    labels:
      app: ${APP}
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ${LOG}:main
    source:
      type: Git
      git:
        uri: ${GIT_HOST}/${ORG}/${LOG}.git
        ref: ${PROD}
    strategy:
      type: Docker
    triggers:
    - type: ConfigChange
    - type: GitHub
      github:
        secret: ${GITHUB_SECRET}
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: ${APP}
    labels:
      app: ${APP}
  spec:
    lookupPolicy:
      local: true
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: ${DEV}-${APP}
    labels:
      app: ${APP}
  spec:
    lookupPolicy:
      local: true
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: ${LOG}
    labels:
      app: ${APP}
  spec:
    lookupPolicy:
      local: true
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: ${APP}
    labels:
      app: ${APP}
  spec:
    replicas: ${{REPS}}
    selector:
      app: ${APP}
      deploymentconfig: ${APP}
    template:
      metadata:
        labels:
          app: ${APP}
          deploymentconfig: ${APP}
      spec:
        containers:
        - image: ${APP}:${TAG}
          name: ${APP}
          ports:
          - containerPort: ${APP_PORT}
          volumeMounts:
          - mountPath: ${HOME}/${LOG_DIR}
            name: ${LOG}
          - mountPath: ${HOME}/${TMP_DIR}
            name: ${TMP_DIR}
          livenessProbe:
            httpGet:
              path: /${HEALTH}
              port: ${{APP_PORT}}
            failureThreshold: ${{FAILURE_THRESHOLD}}
            periodSeconds: ${{LIVENESS_PERIOD}}
          readinessProbe:
            httpGet:
              path: /${HEALTH}
              port: ${{APP_PORT}}
            initialDelaySeconds: ${{READINESS_PERIOD}}
            periodSeconds: ${{READINESS_PERIOD}}
          env:
          - name: PAGE_TITLE
            value: ${APP_TITLE}
          - name: BRANCH
            value: ${PROD}
          - name: FINBIF_ACCESS_TOKEN
            value: ${FINBIF_ACCESS_TOKEN}
          - name: FINBIF_API
            value: ${FINBIF_API}
          - name: FINBIF_WAREHOUSE_QUERY
            value: ${FINBIF_WAREHOUSE_QUERY}
          - name: FINBIF_EMAIL
            value: ${FINBIF_EMAIL}
          - name: PGUSER
            value: ${DB}
          - name: PGPASSWORD
            value: ${DB_PASSWORD}
          - name: PGHOST
            value: ${DB}
        volumes:
        - name: ${LOG}
          persistentVolumeClaim:
            claimName: ${LOG}
        - name: ${TMP_DIR}
          emptyDir:
            medium: Memory
    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - ${APP}
        from:
          kind: ImageStreamTag
          name: ${APP}:${TAG}
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: ${DEV}-${APP}
    labels:
      app: ${APP}
  spec:
    replicas: ${{REPS}}
    selector:
      app: ${APP}
      deploymentconfig: ${DEV}-${APP}
    template:
      metadata:
        labels:
          app: ${APP}
          deploymentconfig: ${DEV}-${APP}
      spec:
        containers:
        - image: ${DEV}-${APP}:${TAG}
          name: ${DEV}-${APP}
          ports:
          - containerPort: ${APP_PORT}
          volumeMounts:
          - mountPath: ${HOME}/${LOG_DIR}
            name: ${DEV}-${LOG}
          - mountPath: ${HOME}/${TMP_DIR}
            name: ${TMP_DIR}
          livenessProbe:
            httpGet:
              path: /${HEALTH}
              port: ${{APP_PORT}}
            failureThreshold: ${{FAILURE_THRESHOLD}}
            periodSeconds: ${{LIVENESS_PERIOD}}
          readinessProbe:
            httpGet:
              path: /${HEALTH}
              port: ${{APP_PORT}}
            initialDelaySeconds: ${{READINESS_PERIOD}}
            periodSeconds: ${{READINESS_PERIOD}}
          env:
          - name: PAGE_TITLE
            value: ${APP_TITLE}-${DEV}
          - name: BRANCH
            value: ${DEV}
          - name: FINBIF_ACCESS_TOKEN
            value: ${DEV_FINBIF_ACCESS_TOKEN}
          - name: FINBIF_API
            value: ${DEV_FINBIF_API}
          - name: FINBIF_WAREHOUSE_QUERY
            value: ${DEV_FINBIF_WAREHOUSE_QUERY}
          - name: FINBIF_EMAIL
            value: ${FINBIF_EMAIL}
          - name: PGUSER
            value: ${DB}
          - name: PGPASSWORD
            value: ${DEV_DB_PASSWORD}
          - name: PGHOST
            value: ${DEV}-{DB}
        volumes:
        - name: ${DEV}-${LOG}
          persistentVolumeClaim:
            claimName: ${DEV}-${LOG}
        - name: ${TMP_DIR}
          emptyDir:
            medium: Memory
    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - ${DEV}-${APP}
        from:
          kind: ImageStreamTag
          name: ${DEV}-${APP}:${TAG}
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: ${DB}
    labels:
      app: ${APP}
  spec:
    replicas: 1
    selector:
      app: ${APP}
      deploymentconfig: ${DB}
    template:
      metadata:
        labels:
          app: ${APP}
          deploymentconfig: ${DB}
      spec:
        containers:
        - image: ${DB}
          name: ${DB}
          volumeMounts:
          - mountPath: ${DB_DIR}
            name: ${DB}
          ports:
            - containerPort: ${DB_PORT}
          env:
          - name: POSTGRES_USER
            value: ${DB}
          - name: POSTGRES_PASSWORD
            value: ${DB_PASSWORD}
          - name: POSTGRESQL_DATABASE
            value: ${DB}
        volumes:
        - name: ${DB}
          persistentVolumeClaim:
            claimName: ${DB}
    triggers:
    - type: ConfigChange
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: ${DEV}-${DB}
    labels:
      app: ${APP}
  spec:
    replicas: 1
    selector:
      app: ${APP}
      deploymentconfig: ${DEV}-${DB}
    template:
      metadata:
        labels:
          app: ${APP}
          deploymentconfig: ${DEV}-${DB}
      spec:
        containers:
        - image: ${DB_IMAGE}
          name: ${DEV}-${DB}
          volumeMounts:
          - mountPath: ${DB_DIR}
            name: ${DEV}-${DB}
          ports:
            - containerPort: ${DB_PORT}
          env:
          - name: POSTGRESQL_USER
            value: ${DB}
          - name: POSTGRESQL_PASSWORD
            value: ${DEV_DB_PASSWORD}
          - name: POSTGRESQL_DATABASE
            value: ${DB}
        volumes:
        - name: ${DEV}-${DB}
          persistentVolumeClaim:
            claimName: ${DEV}-${DB}
    triggers:
    - type: ConfigChange
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: ${LOG}
    labels:
      app: ${APP}
  spec:
    replicas: ${{REPS}}
    selector:
      app: ${APP}
      deploymentconfig: ${LOG}
    template:
      metadata:
        labels:
          app: ${APP}
          deploymentconfig: ${LOG}
      spec:
        containers:
        - image: ${LOG}:${TAG}
          name: ${LOG}
          ports:
          - containerPort: ${LOG_PORT}
          volumeMounts:
          - mountPath: ${HOME}/${LOG_DIR}
            name: ${LOG}
          livenessProbe:
            httpGet:
              port: ${{LOG_PORT}}
            failureThreshold: ${{FAILURE_THRESHOLD}}
            periodSeconds: ${{LIVENESS_PERIOD}}
          readinessProbe:
            httpGet:
              port: ${{LOG_PORT}}
            initialDelaySeconds: ${{READINESS_PERIOD}}
            periodSeconds: ${{READINESS_PERIOD}}
          env:
          - name: PAGE_TITLE
            value: ${APP_TITLE}
        volumes:
        - name: ${LOG}
          persistentVolumeClaim:
            claimName: ${LOG}
    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - ${LOG}
        from:
          kind: ImageStreamTag
          name: ${LOG}:${TAG}
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: ${DEV}-${LOG}
    labels:
      app: ${APP}
  spec:
    replicas: ${{REPS}}
    selector:
      app: ${APP}
      deploymentconfig: ${DEV}-${LOG}
    template:
      metadata:
        labels:
          app: ${APP}
          deploymentconfig: ${DEV}-${LOG}
      spec:
        containers:
        - image: ${LOG}:${TAG}
          name: ${DEV}-${LOG}
          ports:
          - containerPort: ${LOG_PORT}
          volumeMounts:
          - mountPath: ${HOME}/${LOG_DIR}
            name: ${DEV}-${LOG}
          livenessProbe:
            httpGet:
              port: ${{LOG_PORT}}
            failureThreshold: ${{FAILURE_THRESHOLD}}
            periodSeconds: ${{LIVENESS_PERIOD}}
          readinessProbe:
            httpGet:
              port: ${{LOG_PORT}}
            initialDelaySeconds: ${{READINESS_PERIOD}}
            periodSeconds: ${{READINESS_PERIOD}}
          env:
          - name: PAGE_TITLE
            value: ${APP_TITLE}-${DEV}
        volumes:
        - name: ${DEV}-${LOG}
          persistentVolumeClaim:
            claimName: ${DEV}-${LOG}
    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - ${DEV}-${LOG}
        from:
          kind: ImageStreamTag
          name: ${LOG}:${TAG}
- kind: PersistentVolumeClaim
  apiVersion: v1
  metadata:
    name: ${LOG}
  spec:
    accessModes:
    - ReadWriteMany
    persistentVolumeReclaimPolicy: Retain
    resources:
      requests:
        storage: ${SMALL_STORAGE}
- kind: PersistentVolumeClaim
  apiVersion: v1
  metadata:
    name: ${DEV}-${LOG}
  spec:
    accessModes:
    - ReadWriteMany
    persistentVolumeReclaimPolicy: Retain
    resources:
      requests:
        storage: ${SMALL_STORAGE}
- kind: PersistentVolumeClaim
  apiVersion: v1
  metadata:
    name: ${DB}
  spec:
    accessModes:
    - ReadWriteMany
    persistentVolumeReclaimPolicy: Retain
    resources:
      requests:
        storage: ${STORAGE}
- kind: PersistentVolumeClaim
  apiVersion: v1
  metadata:
    name: ${DEV}-${DB}
  spec:
    accessModes:
    - ReadWriteMany
    persistentVolumeReclaimPolicy: Retain
    resources:
      requests:
        storage: ${SMALL_STORAGE}
- kind: Service
  apiVersion: v1
  metadata:
    name: ${APP}
    labels:
      app: ${APP}
  spec:
    ports:
    - name: ${APP_PORT}
      port: ${APP_PORT}
      protocol: TCP
      targetPort: ${{APP_PORT}}
    selector:
      app: ${APP}
      deploymentconfig: ${APP}
- kind: Service
  apiVersion: v1
  metadata:
    name: ${DEV}-${APP}
    labels:
      app: ${APP}
  spec:
    ports:
    - name: ${APP_PORT}
      port: ${APP_PORT}
      protocol: TCP
      targetPort: ${{APP_PORT}}
    selector:
      app: ${APP}
      deploymentconfig: ${DEV}-${APP}
- kind: Service
  apiVersion: v1
  metadata:
    name: ${LOG}
    labels:
      app: ${APP}
  spec:
    ports:
    - name: ${LOG_PORT}
      port: ${LOG_PORT}
      protocol: TCP
      targetPort: ${{LOG_PORT}}
    selector:
      app: ${APP}
      deploymentconfig: ${LOG}
- kind: Service
  apiVersion: v1
  metadata:
    name: ${DEV}-${LOG}
    labels:
      app: ${APP}
  spec:
    ports:
    - name: ${LOG_PORT}
      port: ${LOG_PORT}
      protocol: TCP
      targetPort: ${{LOG_PORT}}
    selector:
      app: ${APP}
      deploymentconfig: ${DEV}-${LOG}
- kind: Service
  apiVersion: v1
  metadata:
    name: ${DB}
    labels:
      app: ${APP}
  spec:
    ports:
    - name: ${DB_PORT}
      port: ${DB_PORT}
      protocol: TCP
      targetPort: ${{DB_PORT}}
    selector:
      app: ${APP}
      deploymentconfig: ${DB}
- kind: Service
  apiVersion: v1
  metadata:
    name: ${DEV}-${DB}
    labels:
      app: ${APP}
  spec:
    ports:
    - name: ${DB_PORT}
      port: ${DB_PORT}
      protocol: TCP
      targetPort: ${{DB_PORT}}
    selector:
      name: postgres
      app: ${APP}
      deploymentconfig: ${DEV}-${DB}
- kind: Route
  apiVersion: v1
  metadata:
    name: ${APP}
    labels:
      app: ${APP}
  spec:
    host: ${SUBDOMAIN}.${HOST}
    port:
      targetPort: ${APP_PORT}
    tls:
      termination: edge
    to:
      kind: Service
      name: ${APP}
    wildcardPolicy: None
- kind: Route
  apiVersion: v1
  metadata:
    name: ${DEV}-${APP}
    labels:
      app: ${APP}
  spec:
    host: ${SUBDOMAIN}-${DEV}.${HOST}
    port:
      targetPort: ${APP_PORT}
    tls:
      termination: edge
    to:
      kind: Service
      name: ${DEV}-${APP}
    wildcardPolicy: None
- kind: Route
  apiVersion: v1
  metadata:
    name: ${LOG}
    labels:
      app: ${APP}
  spec:
    host: ${LOG_SUBDOMAIN}.${LOG_HOST}
    port:
      targetPort: ${LOG_PORT}
    tls:
      termination: edge
    to:
      kind: Service
      name: ${LOG}
    wildcardPolicy: None
- kind: Route
  apiVersion: v1
  metadata:
    name: ${DEV}-${LOG}
    labels:
      app: ${APP}
  spec:
    host: ${LOG_SUBDOMAIN}-${DEV}.${LOG_HOST}
    port:
      targetPort: ${LOG_PORT}
    tls:
      termination: edge
    to:
      kind: Service
      name: ${DEV}-${LOG}
    wildcardPolicy: None
