---
title: "Community temperature index"
author: "William K. Morris"
output: 
  rmarkdown::html_vignette:
    toc: true
vignette: >
  %\VignetteIndexEntry{Community temperature index}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(fig.path = "figure/")
knitr::opts_knit$set(base.dir = "pkg/vignettes/")
```

```{r pkgs, message = FALSE}
library(dplyr, quietly = TRUE)
library(fbi, quietly = TRUE)
library(finbif, quietly = TRUE)
library(ggplot2, quietly = TRUE)
library(lubridate, quietly = TRUE)
library(lme4, quietly = TRUE)
library(arm, quietly = TRUE)
```

```{r survey-select}
select <- c("document_id", "location_id", "year", "month", "day")
```

```{r survey-filter}
filter <- list(
  collection = "Winter Bird Census",
  date_range_ymd = c("1958-12-01", ""),
  date_range_md= c("12-01", "01-31"),
  has_value = select
)
```

```{r surveys}
surveys <- finbif_occurrence(
  filter = filter,
  select = select,
  aggregate = "events",
  aggregate_counts = FALSE,
  n = "all",
  quiet = TRUE
)
```

```{r process-survyes}
surveys <- pick_first_survey_in_winter(surveys)
```

```{r count-filter}
filter[["has_value"]] <- c("document_id", "abundance_interpreted")
```

```{r taxa}
sti <- c(
  "Poecile montanus" = -7.51,
  "Regulus regulus" = -4.23,
  "Lophophanes cristatus" = -5.90,
  "Certhia familiaris" = -6.89
)
```

```{r counts}
counts <- lapply(
  names(sti),
  finbif_occurrence,
  filter = filter,
  select = c("scientific_name", "document_id", "abundance"),
  n = "all",
  quiet = TRUE
)
```

```{r process-counts}
counts <- lapply(counts, combine_with_surveys, surveys)

counts <- do.call(rbind, counts)

counts[["sti"]] <- sti[counts[["scientific_name"]]]

counts <- group_by(counts, location_id, year)
```

```{r model}
cti_data <- summarise(counts, cti = sum(abundance * sti) / sum(abundance))

model <- lmer(cti ~ (1 | location_id) + (1 | year), cti_data)
```

```{r index}
cti <- data.frame(index = coef(model)[["year"]], se = se.coef(model)[["year"]])

cti[["time"]] <- as.integer(row.names(cti))

names(cti) <- c("index", "se", "time")
```

```{r plot-cti}
ggplot(cti) +
aes(
  x = parse_date_time(time, "Y"),
  y = index,
  ymin = index - se,
  ymax = index + se
) +
geom_ribbon(alpha = .2) +
geom_line() +
ylab(NULL) +
xlab(NULL) +
theme_minimal()
```
