---
title: "Single-taxon indicator (trim)"
author: "William K. Morris"
output: 
  rmarkdown::html_vignette:
    toc: true
vignette: >
  %\VignetteIndexEntry{Single-taxon indicator (trim)}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(fig.path = "figure/")
knitr::opts_knit$set(base.dir = "pkg/vignettes/")
```

```{r pkgs, message = FALSE}
library(fbi, quietly = TRUE)
library(finbif, quietly = TRUE)
library(ggplot2, quietly = TRUE)
library(lubridate, quietly = TRUE)
library(rtrim, quietly = TRUE)
```

```{r filter}
filter <- list(
  location_tag = "farmland",
  collection = c(
    "Point counts of breeding terrestrial birds",
    "Line transect censuses of breeding birds"
  ),
  date_range_ymd = c("1979-01-01", "")
)
```

```{r surveys}
surveys <- finbif_occurrence(
  filter = filter,
  select = c("document_id", "location_id", "year", "month", "day"),
  aggregate = "events",
  aggregate_counts = FALSE,
  n = "all",
  quiet = TRUE
)
```

```{r process-survyes}
surveys <- pick_first_survey_in_year(surveys)

surveys <- require_two_years(surveys)
```

```{r counts}
counts <- finbif_occurrence(
  taxa = "Anthus pratensis",
  filter = filter,
  select = c("document_id", abundance = "pair_abundance"),
  n = "all",
  quiet = TRUE
)
```

```{r process-counts}
counts <- zero_fill(counts, surveys)

counts <- sum_by_event(counts)

counts <- remove_all_zero_locations(counts)
```

```{r model}
model <- trim(abundance ~ location_id + year, counts)
```

```{r index}
index <- index(model, base = 28)
```

```{r plot-single-taxon-trim}
ggplot(index) +
aes(
  x = parse_date_time(time, "Y"),
  y = imputed,
  ymin = imputed - se_imp,
  ymax = imputed + se_imp
) +
geom_ribbon(alpha = .2) +
geom_line() +
ylab(NULL) +
xlab(NULL) +
theme_minimal()
```
