---
title: "Community Temperature Indices"
output: 
  rmarkdown::html_vignette:
    toc: true
vignette: >
  %\VignetteIndexEntry{Community Temperature Indices}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
url <- "https://indicators%s.laji.fi/svg/%s?fontsize=16&scale=60"
```

## {.tabset .tabset-fade .tabset-pills}

### Winter Birds

::: {.pkgdown-release}
![Community Temperature Indicator for Winter Birds (Whole of Finland)
](`r sprintf(url, "", "wbcti")` "Winter Bird Community Temperature Index")
:::

::: {.pkgdown-devel}
![Community Temperature Indicator for Winter Birds (Whole of Finland)
](`r sprintf(url, "-dev", "wbcti")` "Winter Bird Community Temperature Index")
:::

### Summer Birds

::: {.pkgdown-release}
![Community Temperature Indicator for Summer Birds (Whole of Finland)
](`r sprintf(url, "", "sbcti")` "Summer Bird Community Temperature Index")
:::

::: {.pkgdown-devel}
![Community Temperature Indicator for Summer Birds (Whole of Finland)
](`r sprintf(url, "-dev", "sbcti")` "Summer Bird Community Temperature Index")
:::

### Farmland Butterflies

::: {.pkgdown-release}
![Community Temperature Indicator for Farmland Butterflies (Whole of Finland)
](`r sprintf(url, "", "bfcti")` "Butterfly Community Temperature Index")
:::

::: {.pkgdown-devel}
![Community Temperature Indicator for Farmland Butterflies (Whole of Finland)
](`r sprintf(url, "-dev", "bfcti")` "Butterfly Community Temperature Index")
:::
